name: test_jax
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - pip:
      - absl-py==2.0.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.1
      - chex==0.1.84
      - contourpy==1.1.1
      - cycler==0.12.1
      - etils==1.5.1
      - flax==0.7.4
      - fonttools==4.43.1
      - fsspec==2023.10.0
      - idna==3.4
      - importlib-resources==6.1.0
      - jax==0.4.19
      - jaxlib==0.4.19+cuda11.cudnn86
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.1
      - msgpack==1.0.7
      - numpy==1.26.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvcc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.4.25
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.18.3
      - opt-einsum==3.3.0
      - optax==0.1.7
      - orbax-checkpoint==0.4.1
      - pillow==10.1.0
      - pooch==1.7.0
      - protobuf==4.24.4
      - pyparsing==3.1.1
      - pyvista==0.42.3
      - pyyaml==6.0.1
      - requests==2.31.0
      - rich==13.6.0
      - scipy==1.11.3
      - scooby==0.9.2
      - tensorstore==0.1.46
      - toolz==0.12.0
      - tqdm==4.66.1
      - urllib3==2.0.7
      - vtk==9.2.6
