name: pinf
channels:
  - fastai
  - conda-forge
dependencies:
  - python=3.10
  - nbdev
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - mayavi
  - tqdm
  - jupyter-server-proxy
  - sunpy
  - astropy
