# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zpinn',
                'doc_host': '',
                'git_url': 'https://github.com/mgjeon/zpinn',
                'lib_path': 'zpinn'},
  'syms': {'zpinn.ode': {'zpinn.ode.F': ('ode.html#f', 'zpinn/ode.py')}}}
