# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zpinn',
                'doc_host': '',
                'git_url': 'https://github.com/mgjeon/zpinn',
                'lib_path': 'zpinn'},
  'syms': { 'zpinn.lowlouode': {'zpinn.lowlouode.find_P_and_a2': ('lowlou_ode.html#find_p_and_a2', 'zpinn/lowlouode.py')},
            'zpinn.ode': { 'zpinn.ode.draw_bvp_solution_y_yp': ('ode.html#draw_bvp_solution_y_yp', 'zpinn/ode.py'),
                           'zpinn.ode.draw_solution_y_with_exact_y': ('ode.html#draw_solution_y_with_exact_y', 'zpinn/ode.py'),
                           'zpinn.ode.draw_solution_y_yp': ('ode.html#draw_solution_y_yp', 'zpinn/ode.py'),
                           'zpinn.ode.solve_and_draw_solution_y_with_exact_y': ( 'ode.html#solve_and_draw_solution_y_with_exact_y',
                                                                                 'zpinn/ode.py')}}}
