# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ode.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ode.ipynb 3
import numpy as np
from scipy.integrate import solve_ivp

# %% ../nbs/00_ode.ipynb 7
def F(t, y):
    return [y[1], -3*y[0] + np.sin(t)]

t_span = [0, 5]
h = 0.1
t = np.arange(t_span[0], t_span[1]+h, h)

y0 = [-np.pi/2, np.pi]
