# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_hmi_bottom.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_hmi_bottom.ipynb 3
import os
import glob
import numpy as np
from sunpy.map import Map
import matplotlib.pyplot as plt
from astropy import units as u
