# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_solar_data_viz.ipynb.

# %% auto 0
__all__ = ['draw_hmi', 'draw_aia']

# %% ../nbs/05_solar_data_viz.ipynb 2
from sunpy.map import Map
import matplotlib.pyplot as plt

# %% ../nbs/05_solar_data_viz.ipynb 3
def draw_hmi(hmi_path):
    hmi_map = Map(hmi_path)
    hmi_map.peek()
    ref_wcs = hmi_map.wcs
    return ref_wcs

def draw_aia(aia_path, ref_wcs, wavelength):
    aia_map = Map(aia_path)
    aia_map.peek()
    obstime = aia_map.observer_coordinate.obstime
    obstime.format = 'iso'
    aia_repro_map = aia_map.reproject_to(ref_wcs)

    fig = plt.figure()
    ax = fig.add_subplot(projection=aia_repro_map)
    aia_repro_map.plot(axes=ax)
    plt.colorbar()
    plt.title(f"AIA {wavelength} Å {obstime.value}")
    plt.show()
